# fly.toml file generated for falling-sea-5390 on 2023-03-14T22:16:46-04:00

app = "falling-sea-5390"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "mia"
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "5001"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 5001
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
